---

- hosts: all
  become: true
  tasks:

  - name: Install Apache2 and PHP packages
    package:
      update_cache: true
      name:
        - apache2
        - libapache2-mod-php
      state: latest
