---

- hosts: all
  become: true
  tasks:

  - name: Install updates
    tags: always
    package:
      upgrade: dist
      update_cache: yes

- hosts: web_servers
  become: true
  tasks:

  - name: Install Apache2 and PHP packages
    tags: apache,apache2,ubuntu
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
  - name: Copy Index.html file
    tags: apache, apache2,ubuntu
    copy:
      src: defaultsite.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB package
    tags: db,mariadb
    package:
      name:
        - mariadb-server
      state: latest
