---

- hosts: all
  become: true
  tasks:

  - name: Install updates
    tags: always
    package:
      upgrade: dist
      update_cache: yes

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles:
    - db_servers
