- name: Install Apache2 and PHP packages
  tags: apache,apache2,ubuntu
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: latest

- name: Start service
  tags: apache,apache2,ubuntu
  service:
    name: apache2
    state: started

- name: Copy Index.html file
  tags: apache, apache2,ubuntu
  copy:
    src: defaultsite.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
